# Generated by Django 6.0.6 on 2026-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlecat',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal Cat'), ('special', 'Special Cat'), ('rare', 'Rare Cat'), ('super_rare', 'Super Rare Cat'), ('uber_rare', 'Uber Rare Cat'), ('legend_rare', 'Legend Rare Cat'), ('limited', 'Limited Cat')], default='normal', max_length=20),
        ),
    ]
