# Generated by Django 6.0.6 on 2026-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_ability_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
