# Generated by Django 6.0.7 on 2026-07-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_ability_battlecat_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Опис (DE)'),
        ),
        migrations.AddField(
            model_name='ability',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Опис (ES)'),
        ),
        migrations.AddField(
            model_name='ability',
            name='description_ja',
            field=models.TextField(blank=True, verbose_name='Опис (JA)'),
        ),
        migrations.AddField(
            model_name='ability',
            name='name_de',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва (DE)'),
        ),
        migrations.AddField(
            model_name='ability',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва (ES)'),
        ),
        migrations.AddField(
            model_name='ability',
            name='name_ja',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва (JA)'),
        ),
    ]
