# Generated by Django 6.0.7 on 2026-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_ability_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecat',
            name='hits_none',
            field=models.BooleanField(default=False, verbose_name='None'),
        ),
    ]
