# Generated by Django 6.0.7 on 2026-07-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_battlecat_hits_none'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('normal', 'Base Form'), ('evolved', 'Evolved Form'), ('true', 'True Form'), ('ultra', 'Ultra Form')], max_length=10, verbose_name='Стадія еволюції')),
                ('name', models.CharField(max_length=150, verbose_name='Назва форми')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cat_forms/', verbose_name='Іконка форми')),
                ('hp_stat', models.IntegerField(default=0, verbose_name="Здоров'я (HP)")),
                ('attack_power', models.IntegerField(default=0, verbose_name='Урон (Attack Power)')),
                ('dps_stat', models.FloatField(default=0.0, verbose_name='DPS')),
                ('name_de', models.CharField(blank=True, max_length=150, verbose_name='Назва (DE)')),
                ('name_es', models.CharField(blank=True, max_length=150, verbose_name='Назва (ES)')),
                ('name_ja', models.CharField(blank=True, max_length=150, verbose_name='Назва (JA)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показу')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='wiki.battlecat', verbose_name='Кіт')),
            ],
            options={
                'verbose_name': 'Форма еволюції',
                'verbose_name_plural': 'Форми еволюції',
                'ordering': ['order', 'id'],
                'unique_together': {('cat', 'stage')},
            },
        ),
    ]
