# Generated by Django 6.0.7 on 2026-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_catform'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecat',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, verbose_name='URL-адреса (латиницею, генерується автоматично з назви)'),
        ),
    ]
