# Generated by Django 6.0.7 on 2026-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_battlecat_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='icon_only',
            field=models.BooleanField(default=False, verbose_name='Показувати тільки іконку (без опису, в один рядок з іншими такими ж)'),
        ),
    ]
