# Generated by Django 6.0.6 on 2026-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_battlecat_hits_none'),
        ('wiki', '0015_ability_icon_only'),
    ]

    operations = [
    ]
